kind: Service                             
apiVersion: v1
metadata:
  name: ecommerce
  labels:
    app: ecommerce
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: ecommerce                    
  type: LoadBalancer    
